---
title: "DataMergeLab"
author: "Liam Niehus-Staab"
date: "10/8/2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

```{r, echo=TRUE}
#### On My Own Questions ####
#1. Read the three files into R, naming them **books**, **authors**, and 
#**book_authors**.
books <- read.csv("~/Shared/F18MAT295/r-tutorials-master/merging/data/books.csv", as.is = TRUE)
authors <- read.csv("~/Shared/F18MAT295/r-tutorials-master/merging/data/authors.csv", as.is = TRUE)
book_authors <- read.csv("~/Shared/F18MAT295/r-tutorials-master/merging/data/book-authors.csv", as.is = TRUE)
```
```{r, echo=TRUE}
#2. Use the appropriate `join` statement to add the ISBNs to the **authors** 
#data table. Why does the resulting data frame have 31 rows instead of 11?
isbn = left_join(authors, book_authors, by=c("authorid" = "authorID"))
#since there are 5 cases of George Martin rows in each dataset, each row in the left
#matches with each each row on the right 5 times. This causes George Martin to have
#25 rows, whereas the other authors only match once. So they only get 1 row. 
head(isbn)
```
```{r, echo=TRUE}
#3. To eliminate the duplicate rows of your data frame from #6 (which we'll assume 
#you named **df2**) run the following code (change the object names to align with 
#your code as necessary):    
isbn = unique(isbn)
head(isbn)
```
```{r, echo=TRUE}
#4. Use the appropriate `join` statement to add the author information table from #3 
#to the **books** data table. 
books = left_join(books,isbn, by = "ISBN")
head(books)
```
```{r, echo=TRUE}
#5. Are there any authors in the **authors** data table that do not correspond to 
#books in the **books** data table? Use an appropriate join statement to determine
#the answer.
sum(row(anti_join(books, authors)))
#0
# So there are no authors that appear in "authors" that arent in "books"
```
```{r, echo=TRUE}
#6. After reading *A Game of Thrones* the student decides to read the rest of the
#series over the summer. `books2.csv` contains the updated books on the student's 
#reading list. Read this file into R, naming it **books2**.
books2 <- read.csv("~/Shared/F18MAT295/r-tutorials-master/merging/data/books2.csv", as.is = TRUE)
```
```{r, echo=TRUE}
#7. Use the same join statement that you did in #4, but using **books2** rather 
#than **books**.
books2 = left_join(books2,isbn, by = "ISBN")
head(books2)
```